version: "3"

services:
  app:
    image: node:18-alpine
    build:
      context: ${SERVICE_SRC_DIR}
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    env_file:
      - .development.env
    environment:
      - VIRTUAL_HOST=${SERVICE_DOMAIN}
      - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - PORT=${PORT}
    depends_on: 
      - postgres
    networks:
      - back
      - reverse-proxy

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - ${POSTGRES_PORT}
    networks:
      - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

volumes:
  pgdata: