services:
  farm-api:
    container_name: farm-api
    image: node:18-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on: 
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      PG_DATA: /var/lib/postgresql/data
    # 54320 port for accessing from the local machine
    ports:
      - 54320:5432
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

volumes:
  pgdata:
  redis:
    driver: local